version: '3'

services:
  space-cloud-db:
    container_name: space_cloud_database
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=space-cloud-db
      - MYSQL_PASSWORD=123456